apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tator
  region: us-east-2
  version: "1.17"
nodeGroups:
  - name: cpuWorkers
    instanceType: m5.xlarge
    labels:
      cpuWorker: "yes"
      gpuWorker: "no"
      webServer: "yes"
      dbServer: "no"
    minSize: 1
    maxSize: 10
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/node-template/label/cpuWorker: "yes"
      k8s.io/cluster-autoscaler/node-template/label/gpuWorker: "no"
      k8s.io/cluster-autoscaler/node-template/label/webServer: "yes"
      k8s.io/cluster-autoscaler/node-template/label/dbServer: "no"
  - name: gpuWorkers
    instanceType: g4dn.xlarge
    labels:
      cpuWorker: "no"
      gpuWorker: "yes"
      webServer: "no"
      dbServer: "no"
    minSize: 0
    maxSize: 10
    desiredCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/node-template/label/cpuWorker: "no"
      k8s.io/cluster-autoscaler/node-template/label/gpuWorker: "yes"
      k8s.io/cluster-autoscaler/node-template/label/webServer: "no"
      k8s.io/cluster-autoscaler/node-template/label/dbServer: "no"
fargateProfiles:
  - name: fargate
    selectors:
      - namespace: default
        labels:
          app: gunicorn
      - namespace: default
        labels:
          app: tusd
      - namespace: default
        labels:
          app: nginx
      - namespace: default
        labels:
          app: daphne
  - name: fargate-workflows
    selectors:
      - namespace: default
        labels:
          app: move
