{
 "title": "Tator Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container=\"tator-online\"}) by (kube_pod_labels)",
     "legendFormat": "Gunicorn pod count"
    },
    {
     "expr": "count(container_memory_usage_bytes{container=\"nginx\"}) by (kube_pod_labels)",
     "legendFormat": "Nginx pod count"
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"tator-online\"}[1m]))",
     "legendFormat": "CPU utilization (gunicorn)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"nginx\"}[1m]))",
     "legendFormat": "CPU utilization (nginx)"
    }
   ]
  },
  { "title": "REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "REST Request Duration (percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "django_request_latency_seconds{endpoint=\"Medias\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "Medias ({{quantile}})"
    },
    {
     "expr": "django_request_latency_seconds{endpoint=\"Localizations\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "Localizations ({{quantile}})"
    },
    {
     "expr": "django_request_latency_seconds{endpoint=\"States\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "States ({{quantile}})"
    },
    {
     "expr": "django_request_latency_seconds{endpoint=\"LocalizationGraphic\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "LocalizationGraphic ({{quantile}})"
    },
    {
     "expr": "django_request_latency_seconds{endpoint=\"GetFrame\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "GetFrame ({{quantile}})"
    },
    {
     "expr": "django_request_latency_seconds{endpoint=\"Projects\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "Projects ({{quantile}})"
    },
    {
     "expr": "django_request_latency_seconds{endpoint=\"Transcode\", quantile=\"0.99\", path=\"\"}",
     "legendFormat": "Transcode ({{quantile}})"
    }
   ]
  },
  {
   "title": "REST Request Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(django_request_count{endpoint=\"Medias\", instance=~\".*\"}[1m]))",
     "legendFormat": "Medias"
    },
    {
     "expr": "sum(rate(django_request_count{endpoint=\"Localizations\", instance=~\".*\"}[1m]))",
     "legendFormat": "Localizations"
    },
    {
     "expr": "sum(rate(django_request_count{endpoint=\"States\", instance=~\".*\"}[1m]))",
     "legendFormat": "States"
    },
    {
     "expr": "sum(rate(django_request_count{endpoint=\"LocalizationGraphic\", instance=~\".*\"}[1m]))",
     "legendFormat": "LocalizationGraphic"
    },
    {
     "expr": "sum(rate(django_request_count{endpoint=\"GetFrame\", instance=~\".*\"}[1m]))",
     "legendFormat": "GetFrame"
    },
    {
     "expr": "sum(rate(django_request_count{endpoint=\"Projects\", instance=~\".*\"}[1m]))",
     "legendFormat": "Projects"
    },
    {
     "expr": "sum(rate(django_request_count{endpoint=\"Transcode\", instance=~\".*\"}[1m]))",
     "legendFormat": "Transcode"
    }
   ]
  },
  { "title": "Gunicorn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Gunicorn Request Duration (percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gunicorn_request_duration[1m])",
     "legendFormat": "Request duration ({{quantile}})"
    }
   ]
  },
  {
   "title": "Gunicorn Request Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(gunicorn_requests[1m])", "legendFormat": "Request rate" },
    {
     "expr": "rate(gunicorn_request_status_400[1m])",
     "legendFormat": "Error rate (400)"
    },
    {
     "expr": "rate(gunicorn_request_status_404[1m])",
     "legendFormat": "Error rate (404)"
    }
   ]
  }
 ]
}