os: linux
arch: amd64
dist: focal
language: generic
vm:
  size: x-large

addons:
  hosts:
    - travisdev
  snaps:
    - name: microk8s
      confinement: classic
      channel: 1.19/stable

script:
- sudo sleep 120
- sudo microk8s status --wait-ready --timeout 120
- sudo microk8s kubectl get all -A
- sudo microk8s kubectl get no
- sudo microk8s kubectl describe no
- sudo microk8s stop
- sudo hostname localhost
- sudo echo "--hostname-override=127.0.0.1" >> /var/snap/microk8s/current/args/kubelet
- sudo microk8s start
- sudo microk8s status --wait-ready --timeout 120
- sudo microk8s kubectl get all -A
- sudo microk8s kubectl get no
- sudo microk8s kubectl describe no
- sudo journalctl -n 3000 -u snap.microk8s.daemon-containerd
- sudo journalctl -n 3000 -u snap.microk8s.daemon-kubelet
- sudo journalctl -n 3000 -u snap.microk8s.daemon-proxy
- sudo journalctl -n 3000 -u snap.microk8s.daemon-apiserver
- sudo microk8s.inspect
