os: linux
arch: amd64
dist: focal
language: generic
vm:
  size: x-large

addons:
  snaps:
    - name: microk8s
      confinement: classic
      channel: 1.19/stable

script:
- sudo microk8s status --wait-ready
