apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: echo-           # name of the workflow spec
spec:
  entrypoint: echo          # invoke the whalesay template
  templates:
    - name: echo              # name of the template
      container:
        image: busybox
        command: [ echo ]
        args: [ "{{ message }}" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
