FROM node:20.11.1-alpine
# This assumes npm install has been run in the ui directory
COPY scripts/packages/tator-js /tator_online/scripts/packages/tator-js
COPY ui /tator_online/ui
WORKDIR /tator_online/ui
