FROM cvisionai/a1_encoder:v0.0.2 AS cvtranscoder
MAINTAINER CVision AI <info@cvisionai.com>
# Install apt packages
# Install apt packages
RUN yum install -y \
        python39 python39-pip \
        python39-setuptools python39-devel gcc gcc-c++ git vim curl unzip wget \
        freetype cmake zlib-devel libjpeg libtiff-devel libwebp-devel libjpeg-turbo-devel

ENV PATH="/opt/cvision/bin/:$PATH"

# Copy over scripts
COPY scripts/transcoder /scripts
COPY scripts/packages/tator-py/dist/*.whl /tmp

# Build tator-py
RUN pip3 install tmp/*.whl

WORKDIR /scripts
