FROM cvisionai/a1_encoder:v0.0.3 AS cvtranscoder
MAINTAINER CVision AI <info@cvisionai.com>
# Install apt packages
# Install apt packages

ENV PATH="/opt/cvision/bin/:$PATH"

# Copy over scripts
COPY scripts/transcoder /scripts
COPY scripts/packages/tator-py/dist/*.whl /tmp

# Build tator-py
RUN pip3 install /tmp/*.whl

WORKDIR /scripts
