{{- if index .Values "kube-prometheus-stack" "enabled" }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  minReplicas: {{ .Values.hpa.nginxMinReplicas }}
  maxReplicas: {{ .Values.hpa.nginxMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
{{- if index .Values "kube-prometheus-stack" "enabled" }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: nginx_http_requests_per_second
      target:
        type: AverageValue
        averageValue: 10m
{{- else }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.nginxCpuPercent }}
{{- end }}
---
{{- if index .Values "kube-prometheus-stack" "enabled" }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: gunicorn-hpa
spec:
  minReplicas: {{ .Values.hpa.gunicornMinReplicas }}
  maxReplicas: {{ .Values.hpa.gunicornMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gunicorn-deployment
{{- if index .Values "kube-prometheus-stack" "enabled" }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: nginx_http_requests_per_second
      target:
        type: AverageValue
        averageValue: 10m
{{- else }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.gunicornCpuPercent }}
{{- end }}
