apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
    type: web
spec:
  selector:
    matchLabels:
      app: ui
      type: web
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
        type: web
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        webServer: "yes"
      containers:
        - name: tator-ui
          image: {{ .Values.dockerRegistry }}/tator_ui:{{ .Values.gitRevision }}
          imagePullPolicy: "Always"
          env:
          - name: DEBUG
            value: "express:*"
          command:
          - npm
          args:
          - run
          - serve
          - --
          - --backend=''
          {{- if .Values.email.enabled }}
          - --email_enabled
          {{- end }}
          {{- if .Values.okta.enabled }}
          - --okta_enabled
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.uiCpuLimit | default "4000m" }}
              memory: {{ .Values.uiMemoryLimit | default "16Gi" }}
            requests:
              cpu: {{ .Values.uiCpuRequest | default "1000m" }}
              memory: {{ .Values.uiMemoryRequest | default "4Gi" }}
          ports:
            - containerPort: 3000
              name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  labels:
    app: ui
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: ui-port
  selector:
    app: ui
    type: web
  type: NodePort
